name: build

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      IMAGE_NAME: sample-app
    name: Build and Run
    steps:
      - uses: actions/checkout@v2
      - name: check environment
        run: echo ${{ env.IMAGE_NAME }}
      - name: check build tools and folder structure
        run: |
          ls
          pwd
          cmake --version
          make --version
          which g++
          which clang++
      - name: build using clang++
        run: |
          ./build_opencv.sh
      - name: check environment
        run: |
          find /usr -name "opencv4.pc"
          find /usr -name "opencv.pc"
          ls /usr/local/lib/pkgconfig
          echo $PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          echo $PKG_CONFIG_PATH
      - name: run main
        run: |
          make
          ./hello.out

